using System.Text.Json.Serialization;
using OuterloopLabApi.External;

namespace OuterloopLabApi.Conversion;

public sealed class ConversionAuditDocument
{
    [JsonPropertyName("id")]
    public string Id { get; set; } = default!;

    // Partition key for point reads by id.
    [JsonPropertyName("pk")]
    public string PartitionKey { get; set; } = default!;

    public string SourceCurrency { get; set; } = default!;
    public string TargetCurrency { get; set; } = default!;
    public decimal OriginalAmount { get; set; }
    public decimal ConvertedAmount { get; set; }
    public decimal AppliedRate { get; set; }

    public string? ProviderBaseCurrency { get; set; }
    public string? ProviderDate { get; set; }
    public string? ProviderSequence { get; set; }

    // Constraint: capture the exact execution timestamp generated by the backend server.
    public DateTimeOffset BackendExecutionTimestampUtc { get; set; }

    public static ConversionAuditDocument Create(
        string auditId,
        string sourceCurrency,
        string targetCurrency,
        decimal originalAmount,
        decimal appliedRate,
        decimal convertedAmount,
        string? providerBaseCurrency,
        string? providerDate,
        string? providerSequence,
        DateTimeOffset backendExecutionTimestampUtc)
    {
        return new ConversionAuditDocument
        {
            Id = auditId,
            PartitionKey = auditId,
            SourceCurrency = sourceCurrency,
            TargetCurrency = targetCurrency,
            OriginalAmount = originalAmount,
            ConvertedAmount = convertedAmount,
            AppliedRate = appliedRate,
            ProviderBaseCurrency = providerBaseCurrency,
            ProviderDate = providerDate,
            ProviderSequence = providerSequence,
            BackendExecutionTimestampUtc = backendExecutionTimestampUtc
        };
    }

    public ConversionAuditResponse ToResponse() => new ConversionAuditResponse
    {
        Id = Id,
        SourceCurrency = SourceCurrency,
        TargetCurrency = TargetCurrency,
        OriginalAmount = OriginalAmount,
        ConvertedAmount = ConvertedAmount,
        AppliedRate = AppliedRate,
        ProviderBaseCurrency = ProviderBaseCurrency,
        ProviderDate = ProviderDate,
        ProviderSequence = ProviderSequence,
        BackendExecutionTimestampUtc = BackendExecutionTimestampUtc
    };
}

public sealed class ConversionAuditResponse
{
    [JsonPropertyName("id")]
    public string Id { get; set; } = default!;

    public string SourceCurrency { get; set; } = default!;
    public string TargetCurrency { get; set; } = default!;
    public decimal OriginalAmount { get; set; }
    public decimal ConvertedAmount { get; set; }
    public decimal AppliedRate { get; set; }

    public string? ProviderBaseCurrency { get; set; }
    public string? ProviderDate { get; set; }
    public string? ProviderSequence { get; set; }

    public DateTimeOffset BackendExecutionTimestampUtc { get; set; }
}
